
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y epel-release
    sudo yum repolist
    sudo yum install -y ansible
  SHELL
end
